### ISSUE TITLE
PIS inválido (ou teste)?

### ISSUE THREAD

**Issue by kyriosdata** [kyriosdata/dados#10]
Ou o gerador do PIS, ou o teste (verificador) ou ambos estão com problemas. Veja erro intermitente abaixo. Código destacado permite verificar se a geração ou a verificação, neste caso, está correta. 

![image](https://user-images.githubusercontent.com/1735792/69051933-734f6d00-09e4-11ea-9826-f976f560ceda.png)

**Comment by Andoly** [comment]
Resolvido, tratado com uma condicional, o verificador estava recebendo valor 11 em algumas condições, logo se verificador == 11, então verificador = 0. Logo o PIS se tornará válido.

**Comment by kyriosdata** [comment]
Nao entendi a logica, contudo, acredito que vc tenha verificado o algoritmo
correspondente.

Fabio

Em seg, 18 de nov de 2019 17:44, Andoly <notifications@github.com> escreveu:
