### ISSUE TITLE
CNPJ inválido (ou testes)?

### ISSUE THREAD

**Issue by kyriosdata** [kyriosdata/dados#9]
Erro intermitente. Ou o teste (verificação do CNPJ) ou a geração do CNPJ, ou até mesmo ambos estão incorretos. 

![image](https://user-images.githubusercontent.com/1735792/69051744-0045f680-09e4-11ea-91a9-62dc95a8139d.png)

**Comment by Andoly** [comment]
Resolvido, tratado com uma condicional, o verificador estava recebendo valor 10 em algumas condições, logo se verificador == 10, então verificador = 0. Logo o CNPJ se tornará válido.
